name: Deploy Flask App to AWS ECR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # - name: Build, tag, and push image to Amazon ECR
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     docker build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
      #     docker tag $ECR_REGISTRY/$ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG::7}
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG::7}

      - name: Update ECS task definition with new image
        run: |
          TASK_DEFINITION_NAME=my-task-def
          CONTAINER_NAME=my-container
          NEW_IMAGE=590183744625.dkr.ecr.ap-south-1.amazonaws.com/my-repo:59afa66

          # Fetch the current task definition
          aws ecs describe-task-definition \
            --task-definition $TASK_DEFINITION_NAME \
            --query "taskDefinition" > task-def.json

          # Update the image in containerDefinitions
          cat task-def.json | \
            jq --arg IMAGE "$NEW_IMAGE" \
              --arg NAME "$CONTAINER_NAME" \
              '.containerDefinitions |= map(if .name == $NAME then .image = $IMAGE else . end)' \
            > new-task-def.json

          # Register new revision
          aws ecs register-task-definition \
            --cli-input-json file://new-task-def.json \
            --query "taskDefinition.taskDefinitionArn" --output text > new-task-def-arn.txt

          # Update service to use new revision
          aws ecs update-service \
            --cluster my-cluster \
            --service my-service \
            --task-definition $(cat new-task-def-arn.txt)

